NaN is displayed if no value exists
#### MERGE
pd.merge(df1, df2, on = 'column_name', how = 'inner') 

###### how = 'inner' -- only common rows 
###### how = 'outer' -- all rows 
###### how = 'left' -- include all rows of left dataframe
###### how = 'outer' -- include all rows of right dataframe

In [ ]:
import numpy as np
import pandas as pd

employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
pd.merge(employees, salaries, on='employee_id', how='inner'), pd.merge(employees, salaries, on='employee_id', how='outer')

In [ ]:
pd.merge(employees, salaries, on='employee_id', how='left'), pd.merge(employees, salaries, on='employee_id', how='right')

#### CONCATENATION
pd.concat( [df1, df2], axis = 0/1 )         // 0 for column, 1 for row

#### JOIN - for non  common attributed dataframes
df1.join(df2, how = 'inner/outer)

In [13]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})
pd.concat([df1, df2], axis = 1 )

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [16]:
df3 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df4 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

df3.join(df4, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0